export default interface Texts {
  ANSWER_REQUIRED_TO_PROCEED: string
  MORE_ANSWERS_REQUIRED_TO_PROCEED: string
  CHANGING_NOT_ALLOWED: string
  SCORE_AND_OUTCOME_SHARE: string
  NO_MORE_CHOICES_ALLOWED: string
}
